# Generated by Django 4.1.3 on 2023-07-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=11, verbose_name='作者姓名')),
                ('age', models.IntegerField(default=18, verbose_name='年龄')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('birthday', models.DateField(default='1986-10-13', verbose_name='作者生日')),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='书名')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='价格')),
                ('info', models.CharField(default='', max_length=100, verbose_name='描述')),
                ('market_price', models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='定价')),
                ('code', models.DecimalField(decimal_places=1, default=50, max_digits=7, verbose_name='工厂价')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=11, verbose_name='股票代码')),
                ('name', models.CharField(default='', max_length=15, verbose_name='股票名称')),
                ('area', models.CharField(default='', max_length=21, verbose_name='股票地区')),
                ('industry', models.CharField(default='', max_length=21, verbose_name='所属行业')),
                ('list_date', models.CharField(default='', max_length=10, verbose_name='上市日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
            ],
            options={
                'db_table': 'tb_code',
            },
        ),
        migrations.CreateModel(
            name='Tactics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(default='', max_length=9, verbose_name='股票代码')),
                ('trade_date', models.DateField(default='', verbose_name='策略时间')),
                ('buy_01', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='第一买点')),
                ('buy_02', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='第二买点')),
                ('stop_win', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='止赢')),
                ('stop_loss', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='止损')),
            ],
            options={
                'db_table': 'tb_tactics',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=30, verbose_name='用户名')),
                ('password', models.CharField(default='', max_length=50, verbose_name='密码')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
