# Generated by Django 4.1.3 on 2023-07-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tactics',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='股票名称'),
        ),
    ]
