# Generated by Django 4.1.3 on 2023-07-12 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_tactics_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tactics',
            options={'ordering': ['-trade_date']},
        ),
    ]
